# Generated by Django 5.0.6 on 2024-07-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pesticides_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticides',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
