# Generated by Django 5.0.6 on 2024-07-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pesticides_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticides',
            name='price',
            field=models.TextField(),
        ),
    ]
