# Generated by Django 5.0.6 on 2024-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_pesticides_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticides',
            name='display',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
